version: '3'
services:
# POSTGRESQL
  postgresDB:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    depends_on:
      - redisDB
# REDIS
  # redisDB:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   volumes:
  #     - ./data/redis:/data
# backend
  api-services:
    build: 
      context: .
      dockerfile: docerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - postgresDB
      - redisDB
    volumes:
      - .:/app

volumes:
  - ./data/postgres:/var/lib/postgresql/data
  - ./data/redis:/data

